version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - ${LEO_PORT:-8888}:80
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: "postgres"
    user: root
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
